language: java
jdk:
  - oraclejdk7
  - openjdk7
env:
  matrix:
    - MAVEN_PROFILE=arq-glassfish-embedded TEST_DATABASE=derby
    - MAVEN_PROFILE=arq-glassfish-embedded TEST_DATABASE=travis-mysql

before_script:
  - mysql -e 'create database jeeventstore_test;'

script: "mvn clean install test-compile surefire:test -P${MAVEN_PROFILE}"

branches:
  only:
    - master
